import 'dart:convert';
import 'dart:ui' show Color;

import 'package:flutter/foundation.dart' show debugPrint;
import 'package:flutter/services.dart' show rootBundle;

import '../models/channel.dart';
import '../models/resource_category.dart';
import 'channel_data.dart';

/// Loads and indexes `assets/data/resource_categories.json` — the app-side
/// copy of Rumuo' 60-category research (see resource_category.dart) —
/// AND every file under `assets/data/resources/`: one per category
/// (`{categoryId}.json`) plus `_general.json` for cross-cutting resources and
/// `_profession_open_catalog.json` for source-verified profession books that
/// carry progression, geography, and license metadata.
///
/// One file per category on purpose — this is what "organized, not
/// complicated" means in practice: `assets/data/resources/` is a literal,
/// browsable checklist of the 60 categories. A file existing (and how
/// many of its 10/10/10 slots are filled) IS the progress tracker; no
/// separate spreadsheet needed. Each entry inside a file also carries a
/// `verifiedOn` + `verificationMethod` field — a permanent audit trail of
/// how it was actually checked, not just a claim made in chat once.
///
/// `resource_categories.json` (the research) is fully regenerated by
/// parse_curriculum.py any time the source docs change. The per-category
/// resource files are the opposite: never bulk-regenerated, only ever
/// grown one confirmed entry at a time.
///
/// The lightweight category index loads during startup. Resource files load
/// asynchronously for the selected scope; full loading remains available to
/// search and discovery callers that explicitly need it.
class ResourceCategoryData {
  ResourceCategoryData._();

  static List<ResourceCategory> _all = const [];
  static List<CurriculumModule> _modules = const [];
  static TaxReform? _taxReform;
  static bool _loaded = false;
  static bool _resourcesLoaded = false;
  static bool _allResourcesLoaded = false;
  static Set<String> _loadedCategoryScope = <String>{};
  static Future<void>? _categoriesInFlight;
  static Future<void>? _resourcesInFlight;

  static bool get isLoaded => _loaded;
  static List<ResourceCategory> get all => _all;
  static List<CurriculumModule> get modules => _modules;
  static TaxReform? get taxReform => _taxReform;

  static final Map<String, ResourceCategory> _byId = {};

  static List<Channel> _verifiedChannels = const [];
  static List<Map<String, String>> _verifiedBlogs = const [];
  static List<VerifiedBook> _verifiedBooks = const [];
  static List<VerifiedSubcategorySource> _verifiedSubcategorySources = const [];
  static final Map<String, Map<String, dynamic>> _resourceFiles = {};

  static List<Channel> get verifiedChannels => _verifiedChannels;
  static List<Map<String, String>> get verifiedBlogs => _verifiedBlogs;
  static List<VerifiedBook> get verifiedBooks => _verifiedBooks;
  static List<VerifiedSubcategorySource> get verifiedSubcategorySources =>
      _verifiedSubcategorySources;

  /// Loads the lightweight category index. This is the only category data
  /// needed before the first screen and onboarding search are usable.
  ///
  /// The in-flight future makes repeated calls from startup and onboarding
  /// share one asset read instead of starting duplicate work.
  static Future<void> loadCategories() {
    if (_loaded) return Future.value();
    final existing = _categoriesInFlight;
    if (existing != null) return existing;

    final future = _loadCategories();
    _categoriesInFlight = future;
    return future;
  }

  static Future<void> _loadCategories() async {
    try {
      final raw = await rootBundle.loadString('assets/data/resource_categories.json');
      final json = jsonDecode(raw) as Map<String, dynamic>;

      _modules = (json['modules'] as List)
          .map((m) => CurriculumModule.fromJson(m as Map<String, dynamic>))
          .toList(growable: false);

      _taxReform = TaxReform.fromJson(json['taxReform'] as Map<String, dynamic>);

      _all = (json['categories'] as List)
          .map((c) => ResourceCategory.fromJson(c as Map<String, dynamic>))
          .toList(growable: false);

      _byId
        ..clear()
        ..addEntries(_all.map((c) => MapEntry(c.id, c)));

      _loaded = true;
    } on Object catch (e) {
      // Never let a bad/missing asset take the app down — the picker and
      // the playbook books just degrade to "not available yet" instead.
      debugPrint('[ResourceCategoryData] categories load failed (non-fatal): $e');
    } finally {
      _categoriesInFlight = null;
    }
  }

  /// Loads only the general resources and the categories selected by the user.
  /// This is the startup path: it avoids downloading the entire research
  /// catalog when the first screen only needs a small, relevant subset.
  static Future<void> loadSelectedResources(Set<String> selectedCategoryIds) {
    final selected = Set<String>.from(selectedCategoryIds);
    if (_allResourcesLoaded ||
        (_resourcesLoaded && _loadedCategoryScope.containsAll(selected))) {
      return Future.value();
    }
    return _loadScopedResources(selected);
  }

  /// Loads all verified resources for the full-text search and discovery
  /// surfaces. The general payload is still the compact boot variant; the
  /// large general book archive remains available from its own indexed source.
  static Future<void> loadVerifiedResources() => _loadScopedResources(null);

  static Future<void> _loadScopedResources(Set<String>? selected) async {
    final existing = _resourcesInFlight;
    if (existing != null) {
      await existing;
      if (selected == null
          ? _allResourcesLoaded
          : _allResourcesLoaded ||
              (_resourcesLoaded && _loadedCategoryScope.containsAll(selected))) {
        return;
      }
    }

    final future = _loadVerifiedResourcesSafely(selected);
    _resourcesInFlight = future;
    await future;
  }

  static Future<void> _loadVerifiedResourcesSafely(Set<String>? selected) async {
    try {
      await loadCategories();
      await _loadVerifiedResources(selectedCategoryIds: selected);
      _resourcesLoaded = true;
      _allResourcesLoaded = selected == null;
      _loadedCategoryScope = selected == null
          ? _all.map((category) => category.id).toSet()
          : Set<String>.from(selected);
    } on Object catch (e) {
      debugPrint('[ResourceCategoryData] verified resources load failed (non-fatal): $e');
    } finally {
      _resourcesInFlight = null;
    }
  }

  /// Idempotent full load for callers that need both the category index and
  /// all verified resources before continuing.
  static Future<void> load() async {
    await loadCategories();
    await loadVerifiedResources();
  }

  static Future<void> _loadVerifiedResources({
    required Set<String>? selectedCategoryIds,
  }) async {
    final channels = <Channel>[];
    final blogs = <Map<String, String>>[];
    final books = <VerifiedBook>[];
    final subcategorySources = <VerifiedSubcategorySource>[];

    final categoryIds = selectedCategoryIds == null
        ? _all.map((category) => category.id).toSet()
        : selectedCategoryIds;
    final categoriesToLoad = _all
        .where((category) => categoryIds.contains(category.id))
        .toList(growable: false);

    // Resource files are independent, so read the selected scope in parallel.
    // The startup path uses the small general boot file; full-load callers
    // (notably search) still receive the complete general book archive.
    final generalAsset = selectedCategoryIds == null
        ? '_general.json'
        : '_general_boot.json';
    final results = await Future.wait([
      for (final category in categoriesToLoad)
        _tryLoadResourceFile('assets/data/resources/${category.id}.json'),
      _tryLoadResourceFile('assets/data/resources/$generalAsset'),
      _tryLoadResourceFile('assets/data/resources/_profession_open_catalog.json'),
    ]);

    // _addFrom still runs in a fixed, deterministic order — category order,
    // then general and the profession overlay — regardless of which order the
    // concurrent reads above actually completed in, so combined lists stay
    // stable across runs.
    _resourceFiles.clear();
    for (var i = 0; i < categoriesToLoad.length; i++) {
      final map = results[i];
      if (map == null) continue;
      final category = categoriesToLoad[i];
      _resourceFiles[category.id] = map;
      _addFrom(map, category.id, channels, blogs, books, subcategorySources);
    }

    // The general/cross-cutting resources — not tied to any category, so
    // resourceCategoryId stays null and they flow through
    // ChannelData.eagerFor() (and the equivalent scoping in
    // BlogRssService/FeedProvider) as always-on, exactly like the
    // original 12 channels.
    final general = results[categoriesToLoad.length];
    if (general != null) {
      _resourceFiles['_general'] = general;
      _addFrom(general, null, channels, blogs, books, subcategorySources);
    }

    // The profession overlay is a checked-in, source-verified extension for
    // the 20 profession files. Its grouped shape lets one open textbook be
    // reused across related professions without copying it into every large
    // category JSON file, while categoryId is still preserved on each book.
    final professionOverlay = results[categoriesToLoad.length + 1];
    if (professionOverlay != null) {
      _resourceFiles['_profession_open_catalog'] = professionOverlay;
      for (final group in (professionOverlay['categories'] as List? ?? [])) {
        try {
          final groupMap = group as Map<String, dynamic>;
          final categoryId = (groupMap['categoryId'] as String? ?? '').trim();
          if (categoryId.isEmpty) continue;
          _addFrom(groupMap, categoryId, channels, blogs, books, subcategorySources);
        } on Object catch (e) {
          debugPrint('[ResourceCategoryData] skipping bad profession overlay group: $e');
        }
      }
    }

    _verifiedChannels = List.unmodifiable(channels);
    _verifiedBlogs = List.unmodifiable(blogs);
    _verifiedBooks = List.unmodifiable(books);
    _verifiedSubcategorySources = List.unmodifiable(subcategorySources);

    // The verified channels are now in ResourceCategoryData.verifiedChannels.
    // Invalidate ChannelData's lazy caches so the next access to
    // ChannelData.combined / ChannelData.byId picks up the full channel set
    // instead of returning a stale build from before this load completed.
    ChannelData.invalidateCache();
  }

  static Future<Map<String, dynamic>?> _tryLoadResourceFile(String path) async {
    try {
      final raw = await rootBundle.loadString(path);
      return jsonDecode(raw) as Map<String, dynamic>;
    } on Object {
      // Expected for the ~56 categories not started yet — not logged as
      // an error, this is the normal "not verified yet" state.
      return null;
    }
  }

  static void _addFrom(
    Map<String, dynamic> map,
    String? categoryId,
    List<Channel> channels,
    List<Map<String, String>> blogs,
    List<VerifiedBook> books,
    List<VerifiedSubcategorySource> subcategorySources,
  ) {
    for (final source in (map['subcategorySources'] as List? ?? [])) {
      try {
        subcategorySources.add(VerifiedSubcategorySource.fromJson(
            source as Map<String, dynamic>));
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad subcategory source: $e');
      }
    }
    for (final c in (map['channels'] as List? ?? [])) {
      try {
        final ch = c as Map<String, dynamic>;
        // Skip entries whose YouTube channel ID is missing or blank — an empty
        // id collapses all such channels onto the '' key in _videosByChannel,
        // mixes their videos together, and fires an unfetchable RSS URL.
        final rawId = (ch['id'] as String? ?? '').trim();
        if (rawId.isEmpty) {
          debugPrint('[ResourceCategoryData] skipping channel with empty id: '
              '"${ch['name']}" (categoryId=$categoryId)');
          continue;
        }
        channels.add(Channel(
          id: rawId,
          name: ch['name'] as String,
          handle: ch['handle'] as String,
          description: ch['description'] as String? ?? '',
          accentColor: Color(int.parse(ch['accentColor'] as String? ?? '0xFFF0AA1D')),
          category: 'Business of Your Skill',
          focus: ch['focus'] as String? ?? '',
          initials: ch['initials'] as String? ?? '',
          resourceCategoryId: categoryId,
        ));
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad channel entry '
            '(categoryId=$categoryId): $e');
      }
    }
    for (final b in (map['blogs'] as List? ?? [])) {
      try {
        final bl = b as Map<String, dynamic>;
        blogs.add({
          'name': bl['name'] as String,
          'url': bl['url'] as String,
          if (categoryId != null) 'categoryId': categoryId,
        });
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad blog entry '
            '(categoryId=$categoryId): $e');
      }
    }
    for (final bk in (map['books'] as List? ?? [])) {
      try {
        books.add(VerifiedBook.fromJson(bk as Map<String, dynamic>, categoryId: categoryId));
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad book entry '
            '(categoryId=$categoryId): $e');
      }
    }
  }

  /// Raw parsed resource file for one category, e.g. to check "how many
  /// of the 10/10/10 slots are filled" for a progress display.
  static Map<String, dynamic>? verifiedFor(String categoryId) => _resourceFiles[categoryId];

  static ResourceCategory? byId(String id) => _byId[id];

  static List<ResourceCategory> bySection(ResourceSection section) =>
      _all.where((c) => c.section == section).toList(growable: false);

  static CurriculumModule? moduleByCode(String code) =>
      _modules.where((m) => m.code == code).firstOrNull;
}

extension _FirstOrNull<T> on Iterable<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
